// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroDetalleWPF.DAL;

namespace RegistroDetalleWPF.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211015014118_migracion_inicial")]
    partial class migracion_inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("RegistroDetalleWPF.Entidades.Permisos", b =>
                {
                    b.Property<int>("PermisoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("PermisoID");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            PermisoID = 1,
                            Descripcion = "Administrador",
                            Nombre = "Carlos Lopez"
                        },
                        new
                        {
                            PermisoID = 2,
                            Descripcion = "Empleado",
                            Nombre = "Pedro Santana"
                        });
                });

            modelBuilder.Entity("RegistroDetalleWPF.Entidades.Roles", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("INTEGER");

                    b.HasKey("RolID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RegistroDetalleWPF.Entidades.RolesDetalle", b =>
                {
                    b.Property<int>("RolesDetalleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsAsignado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermisoID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RolID")
                        .HasColumnType("INTEGER");

                    b.HasKey("RolesDetalleID");

                    b.HasIndex("PermisoID");

                    b.HasIndex("RolID");

                    b.ToTable("RolesDetalle");
                });

            modelBuilder.Entity("RegistroDetalleWPF.Entidades.RolesDetalle", b =>
                {
                    b.HasOne("RegistroDetalleWPF.Entidades.Permisos", null)
                        .WithMany("RolesDetalle")
                        .HasForeignKey("PermisoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistroDetalleWPF.Entidades.Roles", null)
                        .WithMany("RolesDetalle")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegistroDetalleWPF.Entidades.Permisos", b =>
                {
                    b.Navigation("RolesDetalle");
                });

            modelBuilder.Entity("RegistroDetalleWPF.Entidades.Roles", b =>
                {
                    b.Navigation("RolesDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
